### PR TITLE
Run deployment against a single job in CI closes #204

### LINKED ISSUE #204: [minor] CI deploy step fails when running against a tag
image

Example: https://travis-ci.org/KristianOellegaard/django-health-check/jobs/443743439

```
Deploying application
running sdist
running egg_info
creating django_health_check.egg-info
writing django_health_check.egg-info/PKG-INFO
writing dependency_links to django_health_check.egg-info/dependency_links.txt
writing top-level names to django_health_check.egg-info/top_level.txt
writing pbr to django_health_check.egg-info/pbr.json
[pbr] Processing SOURCES.txt
writing manifest file 'django_health_check.egg-info/SOURCES.txt'
[pbr] In git context, generating filelist from git
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
writing manifest file 'django_health_check.egg-info/SOURCES.txt'
running check
creating django-health-check-3.8.0
creating django-health-check-3.8.0/django_health_check.egg-info
creating django-health-check-3.8.0/docs
creating django-health-check-3.8.0/health_check
creating django-health-check-3.8.0/health_check/cache
creating django-health-check-3.8.0/health_check/contrib
creating django-health-check-3.8.0/health_check/contrib/celery
creating django-health-check-3.8.0/health_check/contrib/psutil
creating django-health-check-3.8.0/health_check/contrib/rabbitmq
creating django-health-check-3.8.0/health_check/contrib/s3boto3_storage
creating django-health-check-3.8.0/health_check/contrib/s3boto_storage
creating django-health-check-3.8.0/health_check/db
creating django-health-check-3.8.0/health_check/db/migrations
creating django-health-check-3.8.0/health_check/storage
creating django-health-check-3.8.0/health_check/templates
creating django-health-check-3.8.0/health_check/templates/health_check
creating django-health-check-3.8.0/tests
creating django-health-check-3.8.0/tests/testapp
copying files to django-health-check-3.8.0...
copying .editorconfig -> django-health-check-3.8.0
copying .travis.yml -> django-health-check-3.8.0
copying LICENSE -> django-health-check-3.8.0
copying MANIFEST.in -> django-health-check-3.8.0
copying README.rst -> django-health-check-3.8.0
copying requirements-dev.txt -> django-health-check-3.8.0
copying setup.cfg -> django-health-check-3.8.0
copying setup.py -> django-health-check-3.8.0
copying tox.ini -> django-health-check-3.8.0
copying django_health_check.egg-info/PKG-INFO -> django-health-check-3.8.0/django_health_check.egg-info
copying django_health_check.egg-info/SOURCES.txt -> django-health-check-3.8.0/django_health_check.egg-info
copying django_health_check.egg-info/dependency_links.txt -> django-health-check-3.8.0/django_health_check.egg-info
copying django_health_check.egg-info/not-zip-safe -> django-health-check-3.8.0/django_health_check.egg-info
copying django_health_check.egg-info/pbr.json -> django-health-check-3.8.0/django_health_check.egg-info
copying django_health_check.egg-info/top_level.txt -> django-health-check-3.8.0/django_health_check.egg-info
copying docs/changelog.rst -> django-health-check-3.8.0/docs
copying docs/conf.py -> django-health-check-3.8.0/docs
copying docs/contrib.rst -> django-health-check-3.8.0/docs
copying docs/index.rst -> django-health-check-3.8.0/docs
copying docs/readme.rst -> django-health-check-3.8.0/docs
copying docs/settings.rst -> django-health-check-3.8.0/docs
copying health_check/__init__.py -> django-health-check-3.8.0/health_check
copying health_check/backends.py -> django-health-check-3.8.0/health_check
copying health_check/conf.py -> django-health-check-3.8.0/health_check
copying health_check/exceptions.py -> django-health-check-3.8.0/health_check
copying health_check/plugins.py -> django-health-check-3.8.0/health_check
copying health_check/urls.py -> django-health-check-3.8.0/health_check
copying health_check/views.py -> django-health-check-3.8.0/health_check
copying health_check/cache/__init__.py -> django-health-check-3.8.0/health_check/cache
copying health_check/cache/apps.py -> django-health-check-3.8.0/health_check/cache
copying health_check/cache/backends.py -> django-health-check-3.8.0/health_check/cache
copying health_check/contrib/__init__.py -> django-health-check-3.8.0/health_check/contrib
copying health_check/contrib/celery/__init__.py -> django-health-check-3.8.0/health_check/contrib/celery
copying health_check/contrib/celery/apps.py -> django-health-check-3.8.0/health_check/contrib/celery
copying health_check/contrib/celery/backends.py -> django-health-check-3.8.0/health_check/contrib/celery
copying health_check/contrib/celery/tasks.py -> django-health-check-3.8.0/health_check/contrib/celery
copying health_check/contrib/psutil/__init__.py -> django-health-check-3.8.0/health_check/contrib/psutil
copying health_check/contrib/psutil/apps.py -> django-health-check-3.8.0/health_check/contrib/psutil
copying health_check/contrib/psutil/backends.py -> django-health-check-3.8.0/health_check/contrib/psutil
copying health_check/contrib/rabbitmq/__init__.py -> django-health-check-3.8.0/health_check/contrib/rabbitmq
copying health_check/contrib/rabbitmq/apps.py -> django-health-check-3.8.0/health_check/contrib/rabbitmq
copying health_check/contrib/rabbitmq/backends.py -> django-health-check-3.8.0/health_check/contrib/rabbitmq
copying health_check/contrib/s3boto3_storage/__init__.py -> django-health-check-3.8.0/health_check/contrib/s3boto3_storage
copying health_check/contrib/s3boto3_storage/apps.py -> django-health-check-3.8.0/health_check/contrib/s3boto3_storage
copying health_check/contrib/s3boto3_storage/backends.py -> django-health-check-3.8.0/health_check/contrib/s3boto3_storage
copying health_check/contrib/s3boto_storage/__init__.py -> django-health-check-3.8.0/health_check/contrib/s3boto_storage
copying health_check/contrib/s3boto_storage/apps.py -> django-health-check-3.8.0/health_check/contrib/s3boto_storage
copying health_check/contrib/s3boto_storage/backends.py -> django-health-check-3.8.0/health_check/contrib/s3boto_storage
copying health_check/db/__init__.py -> django-health-check-3.8.0/health_check/db
copying health_check/db/apps.py -> django-health-check-3.8.0/health_check/db
copying health_check/db/backends.py -> django-health-check-3.8.0/health_check/db
copying health_check/db/models.py -> django-health-check-3.8.0/health_check/db
copying health_check/db/migrations/0001_initial.py -> django-health-check-3.8.0/health_check/db/migrations
copying health_check/db/migrations/__init__.py -> django-health-check-3.8.0/health_check/db/migrations
copying health_check/storage/__init__.py -> django-health-check-3.8.0/health_check/storage
copying health_check/storage/apps.py -> django-health-check-3.8.0/health_check/storage
copying health_check/storage/backends.py -> django-health-check-3.8.0/health_check/storage
copying health_check/templates/health_check/index.html -> django-health-check-3.8.0/health_check/templates/health_check
copying tests/__init__.py -> django-health-check-3.8.0/tests
copying tests/test_autodiscover.py -> django-health-check-3.8.0/tests
copying tests/test_backends.py -> django-health-check-3.8.0/tests
copying tests/test_cache.py -> django-health-check-3.8.0/tests
copying tests/test_db.py -> django-health-check-3.8.0/tests
copying tests/test_plugins.py -> django-health-check-3.8.0/tests
copying tests/test_rabbitmq.py -> django-health-check-3.8.0/tests
copying tests/test_storage.py -> django-health-check-3.8.0/tests
copying tests/test_views.py -> django-health-check-3.8.0/tests
copying tests/testapp/__init__.py -> django-health-check-3.8.0/tests/testapp
copying tests/testapp/celery.py -> django-health-check-3.8.0/tests/testapp
copying tests/testapp/manage.py -> django-health-check-3.8.0/tests/testapp
copying tests/testapp/settings.py -> django-health-check-3.8.0/tests/testapp
copying tests/testapp/urls.py -> django-health-check-3.8.0/tests/testapp
Writing django-health-check-3.8.0/setup.cfg
creating dist
Creating tar archive
removing 'django-health-check-3.8.0' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading django-health-check-3.8.0.tar.gz
100% 25.3k/25.3k [00:00<00:00, 62.9kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
django_health_check.egg-info/PKG-INFO already exists, no checkout
django_health_check.egg-info/SOURCES.txt already exists, no checkout
django_health_check.egg-info/dependency_links.txt already exists, no checkout
django_health_check.egg-info/not-zip-safe already exists, no checkout
django_health_check.egg-info/pbr.json already exists, no checkout
django_health_check.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

I was wondering how I could help here. It seems to fail to upload the package because it already exists.

Related travis deploy step:
https://github.com/KristianOellegaard/django-health-check/blob/ac7d6198e97f4a151af1a11f81eeb4660e0f5a24/.travis.yml#L29-L38

**HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/**

I quickly searched online and here's the related issue:
https://github.com/travis-ci/travis-ci/issues/10056

The following solution seems right:
https://github.com/travis-ci/travis-ci/issues/10056#issuecomment-437667181

the deploy step should be executed only against one item of the matrix. I can't test this quickly, but I'll join a pull request if you'd like to try. You may confirm this against [Test PyPI](https://packaging.python.org/guides/using-testpypi/), but it requires a separate account and I don't know if this will have the same behaviour. Or you can go cowboy style and test in production on the next release 🤠

✌️

### PR DESCRIPTION
**Pull request by GabLeRoux**
Details in #204

### CODE REVIEW

**Review by codingjoe — COMMENTED** [review]
Good idea, thanks!
However I would prefer a separate build stage:
https://docs.travis-ci.com/user/build-stages/

**Comment by GabLeRoux** [comment]
That would be a better solution indeed. I don't have a setup to test this quickly so I'd let you do it, but a separate build stage is the way to go as it will be way more clear.

**Comment by codingjoe** [comment]
@GabLeRoux I have a working example here: https://github.com/Thermondo/django-heroku-connect/commit/de57d28af7624104b78469ad316565e6b66ab7bb#diff-354f30a63fb0907d4ad57269548329e3

**Comment by GabLeRoux** [comment]
I applied something similar to your example. I did not go further, but I think it should work 👍

**Review by codingjoe — APPROVED** [review]
Looking good! Thanks @GabLeRoux good work 👍

**Pull request merged**
